baseURL = "https://paula-rusti.github.io/"
languageCode = "en-us"
title = "My Blog"
theme = "PaperMod"

[params]
  homeInfoParams = {Title = "Hi, I'm Paula 👋", Content = "Welcome to my blog."}
  ShowReadingTime = true
  ShowPostNavLinks = true